[package]
name = "ez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
eyre = "0.6.5"
toml = "0.5.8"
serde = { version = "1.0.132", features = ["derive"] }
which = "4.2.2"
